Rewite to use pdk

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,94 +1,164 @@
-sudo: required
-
-# Use Travis' Ubuntu Trusty machines. They have more RAM.
-# It does not affect which OSs we are testing, since they all provided
-# by Docker containers. This simply defines which OS Docker itself will
-# be running on.
-dist: trusty
+---
+os: linux
+dist: xenial
 
 services:
   - docker
 
 language: ruby
-
-rvm:
-  - 2.3.4
-
+cache: bundler
+before_install:
+  - bundle -v
+  - rm -f Gemfile.lock
+  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
+  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
+  - "# Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
+  - '[ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION'
+  - gem --version
+  - bundle -v
 script:
-  - docker run --privileged -d polarbearlabs/haveged:1.9.1 # https://github.com/elastic/logstash/issues/5507
-  - |
-    (
-      if [[ -n $TRAVIS_LINT ]]; then
-        make lint
-      elif [[ -n $TRAVIS_UNIT ]]; then
-        bundle exec rake spec
-      else
-        bundle exec rake beaker
-      fi
-    )
-
-env:
-  global:
-    - LOGSTASH_VERSION=6.1.3
-    - BEAKER_PE_DIR=spec/fixtures/artifacts
-    - CI_SPEC_OPTIONS='--format documentation'
-  matrix:
-    # Do linting once.
-    - TRAVIS_LINT=true
-
-    # Run the puppet-rspec synthetic/unit tests.
-    - PUPPET_VERSION=4.6.2 TRAVIS_UNIT=true
-    - PUPPET_VERSION=4.8.2 TRAVIS_UNIT=true
-    - PUPPET_VERSION=4.9.4 TRAVIS_UNIT=true
-    - PUPPET_VERSION=4.10.8 TRAVIS_UNIT=true
-    - PUPPET_VERSION=5.0.1 TRAVIS_UNIT=true
-    - PUPPET_VERSION=5.1.0 TRAVIS_UNIT=true
-    - PUPPET_VERSION=5.2.0 TRAVIS_UNIT=true
-    - PUPPET_VERSION=5.3.3 TRAVIS_UNIT=true
-
-    # Then run the acceptance tests across the matrix.
-    - PUPPET_VERSION=4.6.2 BEAKER_set=centos-6
-    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-6
-    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-6 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=4.6.2 BEAKER_set=centos-7
-    - PUPPET_VERSION=4.7.0 BEAKER_set=centos-7
-    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-7
-    - PUPPET_VERSION=4.9.4 BEAKER_set=centos-7
-    - PUPPET_VERSION=4.10.8 BEAKER_set=centos-7
-    - PUPPET_VERSION=4.10.8 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=5.3.3 BEAKER_set=centos-7
-    - PUPPET_VERSION=5.3.3 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=4.8.2 BEAKER_set=debian-7 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=4.6.2 BEAKER_set=debian-8
-    - PUPPET_VERSION=4.8.2 BEAKER_set=debian-8
-    - PUPPET_VERSION=4.9.4 BEAKER_set=debian-8
-    - PUPPET_VERSION=4.10.8 BEAKER_set=debian-8
-    - PUPPET_VERSION=4.10.8 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=5.3.3 BEAKER_set=debian-8
-    - PUPPET_VERSION=5.3.3 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=4.6.2 BEAKER_set=ubuntu-1404
-    - PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu-1404
-    - PUPPET_VERSION=4.9.4 BEAKER_set=ubuntu-1404
-    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1404
-    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1404
-    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=4.6.2 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=4.9.4 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.4
-
-    - PUPPET_VERSION=5.0.1 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=5.1.0 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=5.2.0 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1604
-    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.4
+  - 'bundle exec rake $CHECK'
+bundler_args: --without system_tests
+rvm:
+  - 2.5.7
+stages:
+  - static
+  - spec
+  - acceptance
+  -
+    if: tag =~ ^v\d
+    name: deploy
+jobs:
+  fast_finish: true
+  include:
+    -
+      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
+      stage: static
+    -
+      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
+      rvm: 2.4.5
+      stage: spec
+    -
+      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
+      rvm: 2.5.7
+      stage: spec
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-6 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-6 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-8 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-8 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-9 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-10 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-10 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1804 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1804 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-2004 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-2004 LOGSTASH_VERSION=5.6.16
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-6 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-6 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-7 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-7 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=centos-8 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=centos-8 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-8 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-8 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-9 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-9 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=debian-10 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=debian-10 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=ubuntu-1804 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-1804 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_set=ubuntu-2004 LOGSTASH_VERSION=6.8.12
+      stage: acceptance
+    -
+      env: DEPLOY_TO_FORGE=yes
+      stage: deploy
